# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_darwin_amd64.tar.gz"
      sha256 "8a345758c0bf1565e254af354e28c05724635a7b183825603cd3b0ba92a74585"
    end
    on_arm do
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_darwin_arm64.tar.gz"
      sha256 "9840e9400715c7cc71a6bcba7b542b205c3b9ba215930f67a5f05c16fa4b524d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_linux_amd64.tar.gz"
      sha256 "81ed27beb79b8e1bebc7a9e389b980eb6babf5a49cf6c79c6589372d8066a3fe"
    end
    on_arm do
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_linux_arm64.tar.gz"
      sha256 "1f422d42f3e5739b7ea601693c32ab752500d01c5d7366be5a5a90714eb44116"
    end
  end

  name "snip"
  desc "CLI proxy that reduces LLM token consumption by 60-90% by filtering shell output"
  homepage "https://github.com/edouard-claude/snip"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  # No zap stanza required

end
