# This file was generated by GoReleaser. DO NOT EDIT.
cask "snip" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "911b48c1487a6ba15e09b9dc60246ef9c638fa01586a316a296030510cc5cb64"
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d46c64d68a4d825e3feb45f0d9a080ba343d507e8c39034041bfe437b4b244e"
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3fa038fb3e23e07cd7e424e0c324f825464c28bfc4e33cbfd7acd9a92ea39e08"
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "08794d3226a46a8002ff555eab9f6191c830df69c37d066ef11e30b5044155fd"
      url "https://github.com/edouard-claude/snip/releases/download/v#{version}/snip_#{version}_linux_arm64.tar.gz"
    end
  end

  name "snip"
  desc "CLI proxy that reduces LLM token consumption by 60-90% by filtering shell output"
  homepage "https://github.com/edouard-claude/snip"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "snip"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snip"]
    end
  end

  # No zap stanza required

end
